language: python
os:
  - linux
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build
install:
  - pip install -r requirements.txt
script:
  - python create_cpp_app.py create "test-app"